name: cd

on:
  push:
    branches: [main]


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Build app
        run: go mod tidy && ./scripts/buildprod.sh

      - name: Run migrations
        run: go install github.com/pressly/goose/v3/cmd/goose@latest && ./scripts/migrateup.sh

      - name: Submit gcloud
        run: echo "gcloud builds submit"
